name: generate

on:
  push:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build 💼
      run: |
        echo "- clone wiki -"
        git clone https://github.com/wavelet-noise/evospace-wiki.git dest
        
        echo "- clone gens -"
        git clone https://github.com/wavelet-noise/evospace-vanilla-gen.git gen
        
        echo "-  generate  -"
        
        echo "---  result  ---"
        rm -rf dest/.git
        rm -rf dest/.github
        rm dest/.gitignore
        rm dest/README.md
    - name: Deploy 🚀
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: gh-pages
        FOLDER: dest
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
